# Generated by Django 5.0.1 on 2024-02-07 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airline_flights_runway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='core.airport'),
        ),
    ]
