# Generated by Django 5.0.2 on 2024-02-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_flights_origin'),
    ]

    operations = [
    ]
