# Generated by Django 5.0.2 on 2024-02-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240207_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight', to='core.airport'),
        ),
    ]
